language: node_js
node_js: stable
cache:
  directories:
    - node_modules
branches:
  only:
    - master
install:
  - npm i
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
